from fastapi import status

# TODO:
#   create not authenticated tests


def test_create_user(client):
    response = client.post(
        '/users',
        json={
            'username': 'test',
            'email': 'testemail@email.com',
            'password': 'password123',
        },
    )

    assert response.json() == {
        'id': 1,
        'username': 'test',
        'email': 'testemail@email.com',
    }
    assert response.status_code == status.HTTP_201_CREATED


def test_create_user_username_in_use(client, user):
    response = client.post(
        '/users',
        json={
            'username': 'test',
            'email': 'otheremail@email.com',
            'password': 'password123',
        },
    )

    assert response.json() == {'detail': 'username or email already in use'}


def test_create_user_email_in_use(client, user):
    response = client.post(
        '/users',
        json={
            'username': 'other_test',
            'email': 'testemail@email.com',
            'password': 'password123',
        },
    )

    assert response.json() == {'detail': 'username or email already in use'}


def test_read_user(client, user, token):
    response = client.get(
        f'/users/{user.id}', headers={'Authorization': f'Bearer {token}'}
    )
    assert response.json() == {
        'id': user.id,
        'username': user.username,
        'email': user.email,
    }
    assert response.status_code == status.HTTP_200_OK


def test_read_non_existent_user(client, token):
    response = client.get('/users/2', headers={'Authorization': f'Bearer {token}'})

    assert response.json() == {'detail': 'user not found'}
    assert response.status_code == status.HTTP_404_NOT_FOUND


# inactive after token implementation
# the test read the /users but there will be an user
# wich is generated by the token fixture
# def test_read_no_users(client, token):
#     response = client.get('/users', headers={'Authorization': f'Bearer {token}'})

#     assert response.json() == {'users': []}
#     assert response.status_code == status.HTTP_200_OK


def test_read_users(client, user, token):
    response = client.get('/users', headers={'Authorization': f'Bearer {token}'})

    assert response.json() == {
        'users': [
            {
                'id': user.id,
                'username': user.username,
                'email': user.email,
            }
        ]
    }
    assert response.status_code == status.HTTP_200_OK


def test_read_user_not_authenticated(client):
    response = client.get('/users/1')

    assert response.json() == {'detail': 'Not authenticated'}
    assert response.status_code == status.HTTP_401_UNAUTHORIZED


def test_read_users_not_authenticated(client):
    response = client.get('/users')

    assert response.json() == {'detail': 'Not authenticated'}
    assert response.status_code == status.HTTP_401_UNAUTHORIZED


def test_update_user(client, user, token):
    # updates the existent user created from the fixture
    response = client.put(
        f'/users/{user.id}',
        json={
            'username': 'newname',
            'email': 'newemail@email.com',
            'password': 'newpwd123',
        },
        headers={'Authorization': f'Bearer {token}'},
    )

    assert response.json() == {
        'id': 1,
        'username': 'newname',
        'email': 'newemail@email.com',
    }
    assert response.status_code == status.HTTP_200_OK


def test_update_user_username_in_use(client, user, token):
    client.post(
        '/users',
        json={
            'username': 'othertest',
            'email': 'otheremail@email.com',
            'password': 'password123',
        },
    )

    response = client.put(
        f'/users/{user.id}',
        json={
            'username': 'othertest',
            'email': 'testemail@email.com',
            'password': 'star-the-repo-if-you-read-me',
        },
        headers={'Authorization': f'Bearer {token}'},
    )

    assert response.json() == {'detail': 'username or email already in use'}
    assert response.status_code == status.HTTP_409_CONFLICT


def test_update_user_email_in_use(client, user, token):
    client.post(
        '/users',
        json={
            'username': 'test1',
            'email': 'email@email.com',
            'password': 'password123',
        },
    )

    response = client.put(
        f'/users/{user.id}',
        json={
            'username': 'othertest',
            'email': 'email@email.com',
            'password': 'star-the-repo-if-you-read-me',
        },
        headers={'Authorization': f'Bearer {token}'},
    )

    assert response.json() == {'detail': 'username or email already in use'}
    assert response.status_code == status.HTTP_409_CONFLICT


# even if the user with id 2 doesn't exist the code will raise 403 forbbiden
# not 404 not found
def test_update_other_user(client, token):
    response = client.put(
        '/users/2',
        json={
            'username': 'test@email.com',
            'email': 'test@email.com',
            'password': 'mysecret123',
        },
        headers={'Authorization': f'Bearer {token}'},
    )

    assert response.json() == {'detail': 'not enough permission'}
    assert response.status_code == status.HTTP_403_FORBIDDEN


def test_update_user_not_authenticated(client):
    response = client.put('/users/1')

    assert response.json() == {'detail': 'Not authenticated'}
    assert response.status_code == status.HTTP_401_UNAUTHORIZED


def test_delete_user(client, user, token):
    response = client.delete(
        f'/users/{user.id}', headers={'Authorization': f'Bearer {token}'}
    )

    assert response.json() == {'message': 'user deleted'}
    assert response.status_code == status.HTTP_200_OK


def test_delete_other_user(client, token):
    response = client.delete('/users/2', headers={'Authorization': f'Bearer {token}'})

    assert response.json() == {'detail': 'not enough permission'}
    assert response.status_code == status.HTTP_403_FORBIDDEN


def test_delete_user_not_authenticated(client):
    response = client.delete('/users/1')

    assert response.json() == {'detail': 'Not authenticated'}
    assert response.status_code == status.HTTP_401_UNAUTHORIZED


# the code only raises 403 forbidden for other users id
# even if the id doesn't exist it will raise 403
# def test_delete_non_existent_user(client):
#     response = client.delete('/users/2')
#
#     assert response.status_code == status.HTTP_404_NOT_FOUND
#     assert response.json() == {'detail': 'user not found'}
