"""removed creator_name FK

Revision ID: 094421a9b6db
Revises: c2fdef741180
Create Date: 2026-03-04 20:25:41.908604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '094421a9b6db'
down_revision: Union[str, Sequence[str], None] = 'c2fdef741180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('creator_name', sa.String(), nullable=False))
    op.add_column('book', sa.Column('creator_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'creator_name')
    op.drop_column('author', 'creator_name')
    # ### end Alembic commands ###
