"""create_books_table

Revision ID: b9546b1721de
Revises: 39b0783e070d
Create Date: 2026-03-02 22:07:37.851568

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b9546b1721de'
down_revision: Union[str, Sequence[str], None] = '39b0783e070d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'book',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.Column('author_id', sa.Integer(), nullable=False),
        sa.Column(
            'genre',
            sa.Enum(
                'FANTASY',
                'ROMANCE',
                'PHILOSOPHY',
                'TERROR',
                'HORROR',
                'COMEDY',
                'SOCIOLOGY',
                'SCIFI',
                'TECHNOLOGY',
                'PHYSICS',
                'MATH',
                'CHEMESTRY',
                'POETRY',
                'DRAMA',
                'MISTERY',
                'BIOGRAPHY',
                'ADVENTURE',
                'SUSPENSE',
                name='bookgenres',
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['author_id'], ['author.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('title'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    # ### end Alembic commands ###
