name: pipeline mdbc api
run-name: ${{ github.actor }} started the CI script
on: [push, pull_request]
jobs:
  Setup-app-environment:
    name: Setup environment for app test
    runs-on: ubuntu-latest
    steps:
      - name: greetings
        run: echo "hello ${{ github.actor }}, you're at ${{ github.repository }}"
