name: pipeline mdbc api
run-name: ${{ github.actor }} started the CI script

on: [push, pull_request]

jobs:
  Setup-app-environment:
    name: Setup environment for app test
    runs-on: ubuntu-latest

    steps:
      - name: logging
        run: echo "${{ github.actor }} performed a ${{ github.event_name }} at ${{ github.repository }}"
      - run: echo "${{ github.run_attempt }}"

